// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sequential

import (
	"context"
	"io"
	"sync"
)

// Ensure, that ClientInterfaceMock does implement ClientInterface.
// If this is not the case, regenerate this file with moq.
var _ ClientInterface = &ClientInterfaceMock{}

// ClientInterfaceMock is a mock implementation of ClientInterface.
//
//	func TestSomethingThatUsesClientInterface(t *testing.T) {
//
//		// make and configure a mocked ClientInterface
//		mockedClientInterface := &ClientInterfaceMock{
//			DownloadMeetingFunc: func(ctx context.Context, url string) (io.ReadCloser, error) {
//				panic("mock out the DownloadMeeting method")
//			},
//			GetMeetingParticipantsFunc: func(ctx context.Context, meetingID string) ([]Participant, error) {
//				panic("mock out the GetMeetingParticipants method")
//			},
//			ListMeetingsFunc: func(ctx context.Context, params *ListMeetingsParams) ([]Meeting, error) {
//				panic("mock out the ListMeetings method")
//			},
//		}
//
//		// use mockedClientInterface in code that requires ClientInterface
//		// and then make assertions.
//
//	}
type ClientInterfaceMock struct {
	// DownloadMeetingFunc mocks the DownloadMeeting method.
	DownloadMeetingFunc func(ctx context.Context, url string) (io.ReadCloser, error)

	// GetMeetingParticipantsFunc mocks the GetMeetingParticipants method.
	GetMeetingParticipantsFunc func(ctx context.Context, meetingID string) ([]Participant, error)

	// ListMeetingsFunc mocks the ListMeetings method.
	ListMeetingsFunc func(ctx context.Context, params *ListMeetingsParams) ([]Meeting, error)

	// calls tracks calls to the methods.
	calls struct {
		// DownloadMeeting holds details about calls to the DownloadMeeting method.
		DownloadMeeting []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
		// GetMeetingParticipants holds details about calls to the GetMeetingParticipants method.
		GetMeetingParticipants []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MeetingID is the meetingID argument value.
			MeetingID string
		}
		// ListMeetings holds details about calls to the ListMeetings method.
		ListMeetings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *ListMeetingsParams
		}
	}
	lockDownloadMeeting        sync.RWMutex
	lockGetMeetingParticipants sync.RWMutex
	lockListMeetings           sync.RWMutex
}

// DownloadMeeting calls DownloadMeetingFunc.
func (mock *ClientInterfaceMock) DownloadMeeting(ctx context.Context, url string) (io.ReadCloser, error) {
	if mock.DownloadMeetingFunc == nil {
		panic("ClientInterfaceMock.DownloadMeetingFunc: method is nil but ClientInterface.DownloadMeeting was just called")
	}
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockDownloadMeeting.Lock()
	mock.calls.DownloadMeeting = append(mock.calls.DownloadMeeting, callInfo)
	mock.lockDownloadMeeting.Unlock()
	return mock.DownloadMeetingFunc(ctx, url)
}

// DownloadMeetingCalls gets all the calls that were made to DownloadMeeting.
// Check the length with:
//
//	len(mockedClientInterface.DownloadMeetingCalls())
func (mock *ClientInterfaceMock) DownloadMeetingCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockDownloadMeeting.RLock()
	calls = mock.calls.DownloadMeeting
	mock.lockDownloadMeeting.RUnlock()
	return calls
}

// GetMeetingParticipants calls GetMeetingParticipantsFunc.
func (mock *ClientInterfaceMock) GetMeetingParticipants(ctx context.Context, meetingID string) ([]Participant, error) {
	if mock.GetMeetingParticipantsFunc == nil {
		panic("ClientInterfaceMock.GetMeetingParticipantsFunc: method is nil but ClientInterface.GetMeetingParticipants was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		MeetingID string
	}{
		Ctx:       ctx,
		MeetingID: meetingID,
	}
	mock.lockGetMeetingParticipants.Lock()
	mock.calls.GetMeetingParticipants = append(mock.calls.GetMeetingParticipants, callInfo)
	mock.lockGetMeetingParticipants.Unlock()
	return mock.GetMeetingParticipantsFunc(ctx, meetingID)
}

// GetMeetingParticipantsCalls gets all the calls that were made to GetMeetingParticipants.
// Check the length with:
//
//	len(mockedClientInterface.GetMeetingParticipantsCalls())
func (mock *ClientInterfaceMock) GetMeetingParticipantsCalls() []struct {
	Ctx       context.Context
	MeetingID string
} {
	var calls []struct {
		Ctx       context.Context
		MeetingID string
	}
	mock.lockGetMeetingParticipants.RLock()
	calls = mock.calls.GetMeetingParticipants
	mock.lockGetMeetingParticipants.RUnlock()
	return calls
}

// ListMeetings calls ListMeetingsFunc.
func (mock *ClientInterfaceMock) ListMeetings(ctx context.Context, params *ListMeetingsParams) ([]Meeting, error) {
	if mock.ListMeetingsFunc == nil {
		panic("ClientInterfaceMock.ListMeetingsFunc: method is nil but ClientInterface.ListMeetings was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *ListMeetingsParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockListMeetings.Lock()
	mock.calls.ListMeetings = append(mock.calls.ListMeetings, callInfo)
	mock.lockListMeetings.Unlock()
	return mock.ListMeetingsFunc(ctx, params)
}

// ListMeetingsCalls gets all the calls that were made to ListMeetings.
// Check the length with:
//
//	len(mockedClientInterface.ListMeetingsCalls())
func (mock *ClientInterfaceMock) ListMeetingsCalls() []struct {
	Ctx    context.Context
	Params *ListMeetingsParams
} {
	var calls []struct {
		Ctx    context.Context
		Params *ListMeetingsParams
	}
	mock.lockListMeetings.RLock()
	calls = mock.calls.ListMeetings
	mock.lockListMeetings.RUnlock()
	return calls
}
